spring.security.user.name=****
spring.security.user.password=****

#// to dont let other wensites use the session id
server.servlet.session.cookie.same-site=strict

spring.datasource.url=jdbc:postgresql://localhost:5432/telusko
spring.datasource.username=postgres
spring.datasource.password=******